# Generated by Django 3.0.3 on 2020-02-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('task_time', models.DateTimeField(verbose_name='select date and time')),
                ('task_added_time', models.DateTimeField()),
                ('task_status', models.BooleanField()),
            ],
        ),
    ]
