# Generated by Django 3.0.3 on 2020-02-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztodoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task_time',
        ),
    ]
