# Generated by Django 3.0.3 on 2020-02-23 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ztodoapp', '0002_remove_todo_task_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task_added_time',
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
