# Generated by Django 3.0.3 on 2020-02-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztodoapp', '0003_auto_20200223_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=25),
        ),
    ]
